In [5]:
import pandas as pd
dict_data={'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

df = pd.DataFrame(dict_data)
print(type(df))

<class 'pandas.DataFrame'>

In [6]:
print(df)

   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [7]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']], index = ['준서', '예은'], columns=['나이', '성별', '학교'])
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [8]:
print(df.index)

Index(['준서', '예은'], dtype='str')

In [9]:
print(df.columns)

Index(['나이', '성별', '학교'], dtype='str')

In [10]:
df.index = ['학생1', '학생2']
df.columns = ['연령', '남녀','소속']

print(df)
print('\n')
print(df.index)
print('\n')
print(df.columns)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중


Index(['학생1', '학생2'], dtype='str')


Index(['연령', '남녀', '소속'], dtype='str')

In [11]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']], index = ['준서', '예은'], columns=['나이', '성별', '학교'])
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [12]:
df = df.rename(columns={'나이':'연령', '성별':'남녀', '학교':'소속'})
print(df)

    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [13]:
df = df.rename(index={'준서':'학생1', '예은':'학생2'})
print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [14]:
exam_data = {'수학': [90,80,70], '영어': [98,89,95], '음악': [85,95,100], '체육': [100,90,90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
print(df)

df2 = df.copy()
df2 = df2.drop('우현')
print(df2)

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [15]:
df3 = df.copy()
df3 = df3.drop(['우현', '인아'], axis = 0)
print(df3)

    수학  영어  음악   체육
서준  90  98  85  100

In [16]:
df4 = df.copy()
df4 = df4.drop(['우현', '인아'], axis = 'index')
print(df4)

    수학  영어  음악   체육
서준  90  98  85  100

In [17]:
df5 = df.copy()
df5 = df5.drop(index = ['우현'])
print(df5)

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [18]:
exam_data = {'수학': [90,80,70], '영어': [98,89,95], '음악': [85,95,100], '체육': [100,90,90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
print(df)
print()
df2 = df.copy()
df2 = df.drop('수학', axis=1)
print(df2)

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [19]:
df3 = df.copy()
df3 = df3.drop(['영어', '음악'], axis = 1)
print(df3)

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [20]:
df4 = df.copy()
df4 = df4.drop(['영어', '음악'], axis = 'columns')
print(df4)

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [21]:
df5 = df.copy()
df5 = df5.drop(columns = '수학')
print(df5)

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [28]:
exam_data = {'수학': [90,80,70], '영어': [98,89,95], '음악': [85,95,100], '체육': [100,90,90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])

label1 = df.loc['서준']
pos1 = df.iloc[0]
print(label1)
print()
print(pos1)

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [26]:
label2 = df.loc[['서준', '우현']]
pos2 = df.iloc[[0,1]]
print(label2)
print()
print(pos2)

sss = df['수학']
print()
print(sss)

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [45]:
label3 = df.loc['서준':'우현']
pos3 = df.iloc[0:1] # iloc는 마지막 숫자 -1까지 출력하기 때문에 위와 결과가 다름
print(label3)
print()
print(pos3)

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

    수학  영어  음악   체육
서준  90  98  85  100

In [110]:
exam_data = {'이름' : ['서준', '우현', '인아'], 
             '수학': [90,80,70], 
             '영어': [98,89,95], 
             '음악': [85,95,100], 
             '체육': [100,90,90]}

df = pd.DataFrame(exam_data)
print(type(df))

<class 'pandas.DataFrame'>

In [111]:
math1 = df['수학']
print(math1)
print()
print(type(math1))

0    90
1    80
2    70
Name: 수학, dtype: int64

<class 'pandas.Series'>

In [112]:
english = df.영어
print(english)
print()
print(type(english))

0    98
1    89
2    95
Name: 영어, dtype: int64

<class 'pandas.Series'>

In [113]:
music_gym = df[['음악', '체육']]
print(music_gym)
print()
print(type(music_gym))

    음악   체육
0   85  100
1   95   90
2  100   90

<class 'pandas.DataFrame'>

In [114]:
math2 = df[['수학']]
print(math2)
print()
print(type(math2))

   수학
0  90
1  80
2  70

<class 'pandas.DataFrame'>

In [115]:
df.loc[::2]

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
2  인아  70  95  100   90

In [116]:
df.loc[0:3:2]

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
2  인아  70  95  100   90

In [117]:
df.loc[::-1]

   이름  수학  영어   음악   체육
2  인아  70  95  100   90
1  우현  80  89   95   90
0  서준  90  98   85  100

In [118]:
exam_data = {'이름' : ['서준', '우현', '인아'], 
             '수학': [90,80,70], 
             '영어': [98,89,95], 
             '음악': [85,95,100], 
             '체육': [100,90,90]}

df = pd.DataFrame(exam_data)

df = df.set_index('이름')
print(df)

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [119]:
a = df.loc['서준', '음악']
print(a)
b = df.iloc[0, 2]
print(b)

85
85

In [120]:
c = df.loc['서준', ['음악', '체육']]
print(c)
d = df.iloc[0, [2, 3]] 
print(d)
e = df.loc['서준', '음악':]
print(e)
f = df.iloc[0, 2:]
print(f)

음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64

In [121]:
g = df.loc[['서준', '우현'], ['음악', '체육']]
print(g)
h = df.iloc[[0,1], [2,3]]
print(h)
i = df.loc['서준':'우현', '음악':]
print(i)
j = df.iloc[0:2, 2:]
print(j)

    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90

In [133]:
exam_data = {
    '이름' : ['서준', '우현', '인아'], 
    '수학': [90,80,70], 
    '영어': [98,89,95], 
    '음악': [85,95,100], 
    '체육': [100,90,90]
    }

df = pd.DataFrame(exam_data)

df['국어'] = 80
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80

In [134]:
df['미술'] = [80,90,100]
df

   이름  수학  영어   음악   체육  국어   미술
0  서준  90  98   85  100  80   80
1  우현  80  89   95   90  80   90
2  인아  70  95  100   90  80  100

In [135]:
exam_data = {'이름' : ['서준', '우현', '인아'], 
             '수학': [90,80,70], 
             '영어': [98,89,95], 
             '음악': [85,95,100], 
             '체육': [100,90,90]}

df = pd.DataFrame(exam_data)

df.loc[3] = 0
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0

In [136]:
df.loc[4] = ['동규', 90,80,70,60]
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0
4  동규  90  80   70   60

In [137]:
exam_data = {'이름' : ['서준', '우현', '인아'], 
             '수학': [90,80,70], 
             '영어': [98,89,95], 
             '음악': [85,95,100], 
             '체육': [100,90,90]}

df = pd.DataFrame(exam_data)

df= df.set_index('이름')
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [138]:
df.iloc[0,3] = 80
df

    수학  영어   음악  체육
이름
서준  90  98   85  80
우현  80  89   95  90
인아  70  95  100  90

In [139]:
df.loc['서준','체육'] = 90
df

    수학  영어   음악  체육
이름
서준  90  98   85  90
우현  80  89   95  90
인아  70  95  100  90

In [140]:
df.loc['서준','체육'] = 90
df

# loc[][] 은 NONO [,] OO

    수학  영어   음악  체육
이름
서준  90  98   85  90
우현  80  89   95  90
인아  70  95  100  90

In [141]:
df.loc['서준', ['음악', '체육']]= 50
df

    수학  영어   음악  체육
이름
서준  90  98   50  50
우현  80  89   95  90
인아  70  95  100  90

In [142]:
df.loc['서준', ['음악', '체육']] = 100, 50
df

    수학  영어   음악  체육
이름
서준  90  98  100  50
우현  80  89   95  90
인아  70  95  100  90

In [143]:
exam_data = {'이름' : ['서준', '우현', '인아'], 
             '수학': [90,80,70], 
             '영어': [98,89,95], 
             '음악': [85,95,100], 
             '체육': [100,90,90]}

df = pd.DataFrame(exam_data)

df = df.transpose()
print(df)

df = df.T
print(df)

      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90
   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90