In [2]:
import pandas as pd

# 딕셔너리 데이터로 판다스 시리즈 만들기
student1 = pd.Series({'국어':100, '영어':80, '수학':90})
print(student1)

국어    100
영어     80
수학     90
dtype: int64

In [3]:
# 학생의 과목별 점수를 200으로 나누기
percentage = student1 / 200

print(percentage)

국어    0.50
영어    0.40
수학    0.45
dtype: float64

In [4]:
print(type(percentage))

<class 'pandas.Series'>

In [5]:
import pandas as pd

# 딕셔너리 데이터로 판다스 시리즈 만들기
student1 = pd.Series({'국어':100, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90, '영어':80})

print(student1)
print('\n')
print(student2)

국어    100
영어     80
수학     90
dtype: int64


수학    80
국어    90
영어    80
dtype: int64

In [6]:
# 두 학생의 과목별 점수로 사칙연산 수행
addition = student1 + student2               #덧셈
print(type(addition))
print(addition)

<class 'pandas.Series'>
국어    190
수학    170
영어    160
dtype: int64

In [7]:
subtraction = student1 - student2            #뺄셈
print(type(subtraction))
print(subtraction)

<class 'pandas.Series'>
국어    10
수학    10
영어     0
dtype: int64

In [8]:
multiplication = student1 * student2         #곱셈
print(type(multiplication))
print(multiplication)

<class 'pandas.Series'>
국어    9000
수학    7200
영어    6400
dtype: int64

In [9]:
division = student1 / student2               #나눗셈
print(type(division))
print(division)

<class 'pandas.Series'>
국어    1.111111
수학    1.125000
영어    1.000000
dtype: float64

In [11]:
# 사칙연산 결과를 데이터프레임으로 합치기 (시리즈 -> 데이터프레임)
result = pd.DataFrame([addition, subtraction, multiplication, division],
                       index=['덧셈', '뺄셈', '곱셈', '나눗셈'
                       ])
result

              국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

In [12]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np

# 딕셔너리 데이터로 판다스 시리즈 만들기
student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90})

print(student1)
print(student2)

국어     NaN
영어    80.0
수학    90.0
dtype: float64
수학    80
국어    90
dtype: int64

In [17]:
# 두 학생의 과목별 점수로 사칙연산 수행 (시리즈 vs. 시리즈)
addition = student1 + student2               #덧셈
subtraction = student1 - student2            #뺄셈
multiplication = student1 * student2         #곱셈
division = student1 / student2               #나눗셈

addition
subtraction
multiplication
division
print(type(division))

<class 'pandas.Series'>

In [12]:
# 사칙연산 결과를 데이터프레임으로 합치기 (시리즈 -> 데이터프레임)
result = pd.DataFrame([addition, subtraction, multiplication, division],
                      index=['덧셈', '뺄셈', '곱셈', '나눗셈'])
print(result)

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [13]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np

# 딕셔너리 데이터로 판다스 시리즈 만들기
student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90})

print(student1)
print(student2)

국어     NaN
영어    80.0
수학    90.0
dtype: float64
수학    80
국어    90
dtype: int64

In [18]:
# 두 학생의 과목별 점수로 사칙연산 수행 (연산 메소드 사용)
sr_add = student1.add(student2, fill_value=0)    #덧셈
sr_sub = student1.sub(student2, fill_value=0)    #뺄셈
sr_mul = student1.mul(student2, fill_value=0)    #곱셈
sr_div = student1.div(student2, fill_value=0)    #나눗셈

# 사칙연산 결과를 데이터프레임으로 합치기 (시리즈 -> 데이터프레임)
result = pd.DataFrame([sr_add, sr_sub, sr_mul, sr_div],
                      index=['덧셈', '뺄셈', '곱셈', '나눗셈'])
result

       국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [20]:
!pip install seaborn

Requirement already satisfied: seaborn in C:\Users\Win11Pro\AppData\Local\Programs\Python\Python314\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\Win11Pro\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in C:\Users\Win11Pro\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\Users\Win11Pro\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\Win11Pro\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\Win11Pro\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\Win11Pro\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\Win11Pro\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\Win11Pro\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=8 in C:\Users\Win11Pro\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\Win11Pro\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\Win11Pro\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Win11Pro\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Win11Pro\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [45]:
# 라이브러리 불러오기
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[ : , ['age','fare']]

print(df.head())   #첫 5행만 표시
print('\n')
print(type(df))
print(titanic.shape)

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500


<class 'pandas.DataFrame'>
(891, 15)

In [16]:
# 데이터프레임에 숫자 10 더하기
addition = df + 10
print(addition.head())   #첫 5행만 표시
print('\n')
print(type(addition))

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500


<class 'pandas.DataFrame'>

In [49]:
# 라이브러리 불러오기
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]
print(df.tail())          #마지막 5행을 표시
print('\n')
print(type(df))

      age   fare
886  27.0  13.00
887  19.0  30.00
888   NaN  23.45
889  26.0  30.00
890  32.0   7.75


<class 'pandas.DataFrame'>

In [50]:
# 데이터프레임에 숫자 10 더하기
addition = df + 10
print(addition.tail())    #마지막 5행을 표시
print('\n')
print(type(addition))

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75


<class 'pandas.DataFrame'>

In [51]:
# 데이터프레임끼리 연산하기 (additon - df)
subtraction = addition - df
print(subtraction.tail())   #마지막 5행을 표시
print('\n')
print(type(subtraction))

      age  fare
886  10.0  10.0
887  10.0  10.0
888   NaN  10.0
889  10.0  10.0
890  10.0  10.0


<class 'pandas.DataFrame'>

In [52]:
# 사칙연산 수행 (연산 메소드 사용)
sample1 = addition.tail(10)
sample2 = subtraction.tail(10).fillna(0.0)

print(sample1)
print(sample2)

      age     fare
881  43.0  17.8958
882  32.0  20.5167
883  38.0  20.5000
884  35.0  17.0500
885  49.0  39.1250
886  37.0  23.0000
887  29.0  40.0000
888   NaN  33.4500
889  36.0  40.0000
890  42.0  17.7500
      age  fare
881  10.0  10.0
882  10.0  10.0
883  10.0  10.0
884  10.0  10.0
885  10.0  10.0
886  10.0  10.0
887  10.0  10.0
888   0.0  10.0
889  10.0  10.0
890  10.0  10.0

In [54]:
df_add = sample1.add(sample2, fill_value=0)    #덧셈
df_sub = sample1.sub(sample2, fill_value=0)    #뺄셈
df_mul = sample1.mul(sample2, fill_value=0)    #곱셈
df_div = sample1.div(sample2, fill_value=0).fillna(0)    #나눗셈

print(df_add)
print()
print(df_sub)
print()
print(df_mul)
print()
print(df_div)

      age     fare
881  53.0  27.8958
882  42.0  30.5167
883  48.0  30.5000
884  45.0  27.0500
885  59.0  49.1250
886  47.0  33.0000
887  39.0  50.0000
888   0.0  43.4500
889  46.0  50.0000
890  52.0  27.7500

      age     fare
881  33.0   7.8958
882  22.0  10.5167
883  28.0  10.5000
884  25.0   7.0500
885  39.0  29.1250
886  27.0  13.0000
887  19.0  30.0000
888   0.0  23.4500
889  26.0  30.0000
890  32.0   7.7500

       age     fare
881  430.0  178.958
882  320.0  205.167
883  380.0  205.000
884  350.0  170.500
885  490.0  391.250
886  370.0  230.000
887  290.0  400.000
888    0.0  334.500
889  360.0  400.000
890  420.0  177.500

     age     fare
881  4.3  1.78958
882  3.2  2.05167
883  3.8  2.05000
884  3.5  1.70500
885  4.9  3.91250
886  3.7  2.30000
887  2.9  4.00000
888  0.0  3.34500
889  3.6  4.00000
890  4.2  1.77500