In [1]:
import pandas as pd

# DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장
exam_data = {'이름' : [ '서준', '우현', '인아'],
             '수학' : [ 90, 80, 70],
             '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100],
             '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data)
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [2]:
# 특정 열(column)을 데이터프레임의 행 인덱스(index)로 설정
ndf = df.set_index(['이름'])
print(ndf)

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [3]:
ndf2 = ndf.set_index('음악')
print(ndf2)

     수학  영어   체육
음악
85   90  98  100
95   80  89   90
100  70  95   90

In [4]:
ndf3 = ndf.set_index(['수학', '음악'])
print(ndf3)

        영어   체육
수학 음악
90 85   98  100
80 95   89   90
70 100  95   90

In [5]:
import pandas as pd

# 딕셔서리를 정의
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

# 딕셔서리를 데이터프레임으로 변환. 인덱스를 [r0, r1, r2]로 지정
df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
print(df)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [6]:
# 인덱스를 [r0, r1, r2, r3, r4]로 재지정
new_index = ['r0', 'r1', 'r2', 'r3', 'r4']
ndf = df.reindex(new_index)
print(ndf)

     c0   c1   c2    c3    c4
r0  1.0  4.0  7.0  10.0  13.0
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN

In [7]:
# reindex로 발생한 NaN값을 숫자 0으로 채우기
new_index = ['r0', 'r1', 'r2', 'r3', 'r4']
ndf2 = df.reindex(new_index, fill_value=0)
print(ndf2)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0

In [8]:
import pandas as pd

# 딕셔서리를 정의
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

# 딕셔서리를 데이터프레임으로 변환. 인덱스를 [r0, r1, r2]로 지정
df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
print(df)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [9]:
# 행 인덱스를 정수형으로 초기화
ndf = df.reset_index()
print(ndf)

  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15

In [10]:
# 행 인덱스를 정수형으로 초기화하고, 기존 인덱스의 열 이름을 지정
ndf2 = df.reset_index(names=['C00'])
print(ndf2)

  C00  c0  c1  c2  c3  c4
0  r0   1   4   7  10  13
1  r1   2   5   8  11  14
2  r2   3   6   9  12  15

In [11]:
# 행 인덱스를 초기화하고, 기존 인덱스를 삭제
ndf3 = df.reset_index(drop=True)
print(ndf3)

   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [12]:
import pandas as pd

# 딕셔서리를 정의
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

# 딕셔서리를 데이터프레임으로 변환. 인덱스를 [r0, r2, r1]로 지정
df = pd.DataFrame(dict_data, index=['r0', 'r2', 'r1'])
print(df)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r2   2   5   8  11  14
r1   3   6   9  12  15

In [13]:
# 내림차순으로 행 인덱스 정렬
ndf = df.sort_index(ascending=False)
print(ndf)

    c0  c1  c2  c3  c4
r2   2   5   8  11  14
r1   3   6   9  12  15
r0   1   4   7  10  13

In [14]:
# 오름차순으로 행 인덱스 정렬
ndf2 = df.sort_index(ascending=True)
print(ndf2)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   3   6   9  12  15
r2   2   5   8  11  14

In [15]:
import pandas as pd

# 딕셔서리를 정의
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,10,11], 'c4':[15,14,14]}

# 딕셔서리를 데이터프레임으로 변환. 인덱스를 [r0, r1, r2]로 지정
df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
print(df)

    c0  c1  c2  c3  c4
r0   1   4   7  10  15
r1   2   5   8  10  14
r2   3   6   9  11  14

In [16]:
# c1 열을 기준으로 내림차순 정렬
ndf = df.sort_values(by='c1', ascending=False)
print(ndf)

    c0  c1  c2  c3  c4
r2   3   6   9  11  14
r1   2   5   8  10  14
r0   1   4   7  10  15

In [17]:
# c2 열을 기준으로 오름차순 정렬
ndf2 = df.sort_values(by='c2', ascending=True)
print(ndf2)

    c0  c1  c2  c3  c4
r0   1   4   7  10  15
r1   2   5   8  10  14
r2   3   6   9  11  14

In [18]:
# c3 열을 기준으로 내림차순 정렬, c4 열을 기준으로 오름차순 정렬
ndf3 = df.sort_values(by=['c3', 'c4'], ascending=[False, True])
print(ndf3)

    c0  c1  c2  c3  c4
r2   3   6   9  11  14
r1   2   5   8  10  14
r0   1   4   7  10  15

In [19]:
import pandas as pd

# 딕셔너리 데이터로 판다스 시리즈 만들기
student1 = pd.Series({'국어':100, '영어':80, '수학':90})
print(student1)

국어    100
영어     80
수학     90
dtype: int64

In [20]:
# 학생의 과목별 점수를 200으로 나누기
percentage = student1 / 200

print(percentage)

국어    0.50
영어    0.40
수학    0.45
dtype: float64

In [21]:
print(type(percentage))

<class 'pandas.Series'>

In [22]:
import pandas as pd

# 딕셔너리 데이터로 판다스 시리즈 만들기
student1 = pd.Series({'국어':100, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90, '영어':80})

print(student1)
print('\n')
print(student2)

국어    100
영어     80
수학     90
dtype: int64


수학    80
국어    90
영어    80
dtype: int64

In [23]:
# 두 학생의 과목별 점수로 사칙연산 수행
addition = student1 + student2               #덧셈
print(type(addition))
print(addition)

<class 'pandas.Series'>
국어    190
수학    170
영어    160
dtype: int64

In [24]:
subtraction = student1 - student2            #뺄셈
print(type(subtraction))
print(subtraction)

<class 'pandas.Series'>
국어    10
수학    10
영어     0
dtype: int64

In [25]:
multiplication = student1 * student2         #곱셈
print(type(multiplication))
print(multiplication)

<class 'pandas.Series'>
국어    9000
수학    7200
영어    6400
dtype: int64

In [26]:
division = student1 / student2               #나눗셈
print(type(division))
print(division)

<class 'pandas.Series'>
국어    1.111111
수학    1.125000
영어    1.000000
dtype: float64

In [27]:
# 사칙연산 결과를 데이터프레임으로 합치기 (시리즈 -> 데이터프레임)
result = pd.DataFrame([addition, subtraction, multiplication, division],
                      index=['덧셈', '뺄셈', '곱셈', '나눗셈'])
print(result)

              국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

In [28]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np

# 딕셔너리 데이터로 판다스 시리즈 만들기
student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90})

print(student1)
print(student2)

국어     NaN
영어    80.0
수학    90.0
dtype: float64
수학    80
국어    90
dtype: int64

In [29]:
# 두 학생의 과목별 점수로 사칙연산 수행 (시리즈 vs. 시리즈)
addition = student1 + student2               #덧셈
subtraction = student1 - student2            #뺄셈
multiplication = student1 * student2         #곱셈
division = student1 / student2               #나눗셈

print(type(division))

<class 'pandas.Series'>

In [30]:
# 사칙연산 결과를 데이터프레임으로 합치기 (시리즈 -> 데이터프레임)
result = pd.DataFrame([addition, subtraction, multiplication, division],
                      index=['덧셈', '뺄셈', '곱셈', '나눗셈'])
print(result)

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [31]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np

# 딕셔너리 데이터로 판다스 시리즈 만들기
student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90})

print(student1)
print(student2)

국어     NaN
영어    80.0
수학    90.0
dtype: float64
수학    80
국어    90
dtype: int64

In [35]:
# 두 학생의 과목별 점수로 사칙연산 수행 (연산 메소드 사용)
sr_add = student1.add(student2, fill_value=0)    #덧셈
sr_sub = student1.sub(student2, fill_value=0)    #뺄셈
sr_mul = student1.mul(student2, fill_value=0)    #곱셈
sr_div = student1.div(student2, fill_value=0)    #나눗셈

# 사칙연산 결과를 데이터프레임으로 합치기 (시리즈 -> 데이터프레임)
result = pd.DataFrame([sr_add, sr_sub, sr_mul, sr_div],
                      index=['덧셈', '뺄셈', '곱셈', '나눗셈'])
print(result)

       국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [36]:
# 라이브러리 불러오기
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]

print(df.head())   #첫 5행만 표시
print('\n')
print(type(df))

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500


<class 'pandas.DataFrame'>

In [37]:
# 데이터프레임에 숫자 10 더하기
addition = df + 10
print(addition.head())   #첫 5행만 표시
print('\n')
print(type(addition))

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500


<class 'pandas.DataFrame'>

In [38]:
# 라이브러리 불러오기
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]
print(df.tail())          #마지막 5행을 표시
print('\n')
print(type(df))

      age   fare
886  27.0  13.00
887  19.0  30.00
888   NaN  23.45
889  26.0  30.00
890  32.0   7.75


<class 'pandas.DataFrame'>

In [39]:
# 데이터프레임에 숫자 10 더하기
addition = df + 10
print(addition.tail())    #마지막 5행을 표시
print('\n')
print(type(addition))

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75


<class 'pandas.DataFrame'>

In [40]:
# 데이터프레임끼리 연산하기 (additon - df)
subtraction = addition - df
print(subtraction.tail())   #마지막 5행을 표시
print('\n')
print(type(subtraction))

      age  fare
886  10.0  10.0
887  10.0  10.0
888   NaN  10.0
889  10.0  10.0
890  10.0  10.0


<class 'pandas.DataFrame'>

In [41]:
# 사칙연산 수행 (연산 메소드 사용)
sample1 = addition.tail()
sample2 = subtraction.tail().fillna(0.0)

print(sample1)
print(sample2)

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75
      age  fare
886  10.0  10.0
887  10.0  10.0
888   0.0  10.0
889  10.0  10.0
890  10.0  10.0

In [42]:
df_add = sample1.add(sample2, fill_value=0)    #덧셈
df_sub = sample1.sub(sample2, fill_value=0)    #뺄셈
df_mul = sample1.mul(sample2, fill_value=0)    #곱셈
df_div = sample1.div(sample2, fill_value=0)    #나눗셈

print(df_add)
print(df_sub)
print(df_mul)
print(df_div)

      age   fare
886  47.0  33.00
887  39.0  50.00
888   0.0  43.45
889  46.0  50.00
890  52.0  27.75
      age   fare
886  27.0  13.00
887  19.0  30.00
888   0.0  23.45
889  26.0  30.00
890  32.0   7.75
       age   fare
886  370.0  230.0
887  290.0  400.0
888    0.0  334.5
889  360.0  400.0
890  420.0  177.5
     age   fare
886  3.7  2.300
887  2.9  4.000
888  NaN  3.345
889  3.6  4.000
890  4.2  1.775

In [43]:
# 라이브러리 불러오기
import pandas as pd
import seaborn as sns

# # titanic 데이터셋 로딩
titanic = sns.load_dataset('titanic')

# 행 인덱스 0~9 범위에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
df = titanic.loc[0:9, ['age','fare']]

# 데이터프레임 출력
df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [44]:
# 조건식 적용 (20세 미만: age < 20)
df['age'] < 20

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9     True
Name: age, dtype: bool

In [45]:
# 불린 인덱싱 (20세 미만의 조건을 충족하는 행을 필터링)
df[df['age'] < 20]

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [46]:
# 불린 인덱싱 (loc 인덱서 활용)
df.loc[df['age'] < 20]

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [47]:
# 불린 인덱싱 (NOT 논리연산)
df.loc[~(df['age'] < 20)]

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
8  27.0  11.1333

In [48]:
# 나이가 10대(10~19세)인 승객 (AND 논리연산)
mask1 = (titanic.age >= 10) & (titanic.age < 20)
df_teenage = titanic[mask1]
df_teenage.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False

In [49]:
# 나이가 10세 미만(0~9세)이고 여성인 승객 (AND 논리연산, loc 인덱서)
mask2 = (titanic.age < 10) & (titanic.sex == 'female')
df_female_under10 = titanic.loc[mask2]
df_female_under10.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
43,1,2,female,3.0,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
58,1,2,female,5.0,1,2,27.7500,S,Second,child,False,NaN,Southampton,yes,False
119,0,3,female,2.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False

In [50]:
# 나이가 10세 미만(0~9세) 또는 60세 이상인 승객 (OR 논리연산)
# age, sex, alone 열만 선택 (loc 인덱서, fancy indexing)
mask3 = (titanic.age < 10) | (titanic.age >= 60)
df_under10_morethan60 = titanic.loc[mask3, ['age', 'sex', 'alone']]
df_under10_morethan60.head()

     age     sex  alone
7    2.0    male  False
10   4.0  female  False
16   2.0    male  False
24   8.0  female  False
33  66.0    male   True

In [51]:
# 불린 시리즈를 새로운 열로 추가
df['age_under_20'] = df['age'] < 20
df.head()

    age     fare  age_under_20
0  22.0   7.2500         False
1  38.0  71.2833         False
2  26.0   7.9250         False
3  35.0  53.1000         False
4  35.0   8.0500         False

In [52]:
# 라이브러리 불러오기
import pandas as pd
import seaborn as sns

# # titanic 데이터셋 로딩
titanic = sns.load_dataset('titanic')

# 행 인덱스 0~9 범위에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
df = titanic.loc[0:9, ['age','fare']]

# 데이터프레임 출력
df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [53]:
# 20세 미만의 조건을 충족하는 행을 필터링
df.query('age < 20')

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [54]:
# 나이가 20세 이상이고 요금이 15 미만인 조건을 모두 충족하는 행을 필터링
df.query('age >= 20 and fare < 15')

    age     fare
0  22.0   7.2500
2  26.0   7.9250
4  35.0   8.0500
8  27.0  11.1333

In [55]:
# 나이가 20세 이상 또는 요금이 15 미만인 조건을 하나라도 충족하는 행을 필터링
df.query('age >= 20 or fare < 15')

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
8  27.0  11.1333

In [56]:
# 라이브러리 불러오기
import seaborn as sns
import pandas as pd

# titanic 데이터셋 로딩
titanic = sns.load_dataset('titanic')

# 디스플레이 설정 변경 - 출력할 최대 열의 개수
pd.set_option('display.max_columns', 10)  
    
# 탑승한 도시가 "Southampton", "Queenstown"인 승객만 따로 추출 - 불린 인덱싱
mask1 = titanic['embark_town'] == "Southampton"
mask2 = titanic['embark_town'].str.match("Queenstown")
df_boolean = titanic[mask1 | mask2]
df_boolean.head()

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True

In [57]:
# isin() 메서드 활용하여 동일한 조건으로 추출
isin_filter = titanic['embark_town'].isin(["Southampton", "Queenstown"])
df_isin = titanic[isin_filter]
df_isin.head()

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True

In [58]:
# 라이브러리 불러오기
import pandas as pd

# 텍스트로 이루어진 시리즈 배열 만들기 (자료형 미지정)
fruit_names = pd.Series(["Apple", "Banana", "Cherry"])

# 시리즈 출력
fruit_names

0     Apple
1    Banana
2    Cherry
dtype: str

In [59]:
# 자료형 지정: 'string' 사용
pd.Series(["Apple", "Banana", "Cherry"], dtype="string")

0     Apple
1    Banana
2    Cherry
dtype: string

In [60]:
# 자료형 지정: pd.StringDtype() 사용
pd.Series(["Apple", "Banana", "Cherry"], dtype=pd.StringDtype())

0     Apple
1    Banana
2    Cherry
dtype: string

In [61]:
# 자료형 변환
fruit_names.astype('string')

0     Apple
1    Banana
2    Cherry
dtype: string

In [62]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np

# 텍스트로 이루어진 시리즈 배열 만들기 (자료형 미지정)
ser = pd.Series(["Apple_사과", "Banana_바나나", "Cherry_체리", np.nan],
               index=["First ", " Second", " Third", "Fourth"])
print(ser)
print("\n")

# 텍스트로 이루어진 시리즈 배열 만들기 (string 자료형 지정)
ser2 = pd.Series(["Apple_사과", "Banana_바나나", "Cherry_체리", np.nan], 
                 index=["First ", " Second", " Third", "Fourth"], dtype="string")
print(ser2)

First        Apple_사과
 Second    Banana_바나나
 Third      Cherry_체리
Fourth            NaN
dtype: str


First        Apple_사과
 Second    Banana_바나나
 Third      Cherry_체리
Fourth           <NA>
dtype: string

In [63]:
# 소문자로 변환
print(ser.str.lower())
print("\n")

# 대문자로 변환
print(ser.str.upper())
print("\n")

# 문자열 길이 계산
print(ser.str.len())

First        apple_사과
 Second    banana_바나나
 Third      cherry_체리
Fourth            NaN
dtype: str


First        APPLE_사과
 Second    BANANA_바나나
 Third      CHERRY_체리
Fourth            NaN
dtype: str


First       8.0
 Second    10.0
 Third      9.0
Fourth      NaN
dtype: float64

In [64]:
# 문자열 분할
print(ser.str.split("_"))
print("\n")

# 문자열을 분할하여 DataFrame으로 확장
print(ser.str.split("_", expand=True))
print("\n")

# 분할된 문자열 중 특정 요소 선택
print(ser.str.split("_").str.get(1))

First        [Apple, 사과]
 Second    [Banana, 바나나]
 Third      [Cherry, 체리]
Fourth               NaN
dtype: object


              0    1
First     Apple   사과
 Second  Banana  바나나
 Third   Cherry   체리
Fourth      NaN  NaN


First       사과
 Second    바나나
 Third      체리
Fourth     NaN
dtype: object

In [65]:
# 행 인덱스를 추출
idx = ser.index
print(idx)

# 양쪽 공백 제거
print(idx.str.strip())

# 왼쪽 공백 제거
print(idx.str.lstrip())

# 오른쪽 공백 제거
print(idx.str.rstrip())

Index(['First ', ' Second', ' Third', 'Fourth'], dtype='str')
Index(['First', 'Second', 'Third', 'Fourth'], dtype='str')
Index(['First ', 'Second', 'Third', 'Fourth'], dtype='str')
Index(['First', ' Second', ' Third', 'Fourth'], dtype='str')

In [70]:
# 문자열 교체("_"을 찾아서 ":"으로 변경)
print(ser.str.replace("_", ":", regex=False))
print("\n")

# 정규 표현식을 사용한 문자열 교체(영문 알파벳이 아닌 문자 제거)
print(ser.str.replace("[^a-zA-Z\\s]", "", regex=True))

First        Apple:사과
 Second    Banana:바나나
 Third      Cherry:체리
Fourth            NaN
dtype: str


First       Apple
 Second    Banana
 Third     Cherry
Fourth        NaN
dtype: str

In [67]:
# 인덱싱 - 각 문자열의 첫 번째 문자 선택
print(ser.str[0])
print("\n")

# 슬라이싱 - 각 문자열의 첫 번째 ~ 3번째 문자 선택
print(ser.str[0:4])

First        A
 Second      B
 Third       C
Fourth     NaN
dtype: str


First      Appl
 Second    Bana
 Third     Cher
Fourth      NaN
dtype: str

In [68]:
# 특정 문자 포함 여부 확인, NA 값을 False로 처리
contains_A = ser.str.contains("A", na=False)
print(contains_A)
print("\n")

# 패턴 포함 여부 확인
contains_pattern = ser.str.contains(r"[A|B][a-z]+")
print(contains_pattern)
print("\n")

# 전체 문자열의 패턴 일치 여부 확인
fullmatch_pattern = ser.str.fullmatch(r"[A|B][a-z]+")
print(fullmatch_pattern)

First       True
 Second    False
 Third     False
Fourth     False
dtype: bool


First       True
 Second     True
 Third     False
Fourth     False
dtype: bool


First      False
 Second    False
 Third     False
Fourth     False
dtype: bool

In [69]:
# 새로운 시리즈 생성
ser3 = pd.Series(["a1", "b2", "c3", "d4a5", "e6e7", "f8"], dtype="string")

# 숫자만 추출
digits = ser3.str.extractall(r"(\d)").groupby(level=0).agg(''.join)
print(digits)
print("\n")

# 알파벳만 추출
letters = ser3.str.extractall(r"([a-z])").groupby(level=0).agg(''.join)
print(letters)
print("\n")

# 숫자를 별도의 컬럼으로 분리
split_columns = ser3.str.extract(r"(?P<Letter>[a-z]+)(?P<Digit>\d+)")
print(split_columns)

    0
0   1
1   2
2   3
3  45
4  67
5   8


    0
0   a
1   b
2   c
3  da
4  ee
5   f


  Letter Digit
0      a     1
1      b     2
2      c     3
3      d     4
4      e     6
5      f     8